name: romi_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Firebase 관련 패키지
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.1

  # ✅ 이미지 선택
  image_picker: ^1.1.2

  # ✅ AI 연동을 위한 HTTP 패키지 추가
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
          weight: 300
