// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYphdqkVcCmOqZwep8nbOPDRZKGsaQeGE',
    appId: '1:553715473254:web:d70b4bcf80e7d6200c46a7',
    messagingSenderId: '553715473254',
    projectId: 'romi-app-bc500',
    authDomain: 'romi-app-bc500.firebaseapp.com',
    storageBucket: 'romi-app-bc500.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtqtcc90zcvKLwvuID-9ddN4za314T6w',
    appId: '1:553715473254:android:091c98c491aa4e880c46a7',
    messagingSenderId: '553715473254',
    projectId: 'romi-app-bc500',
    storageBucket: 'romi-app-bc500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGODPX16b8T4t4Srv6vQRCPuLzK6B89s',
    appId: '1:553715473254:ios:548c0784db11d1ea0c46a7',
    messagingSenderId: '553715473254',
    projectId: 'romi-app-bc500',
    storageBucket: 'romi-app-bc500.firebasestorage.app',
    iosBundleId: 'com.example.romiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGODPX16b8T4t4Srv6vQRCPuLzK6B89s',
    appId: '1:553715473254:ios:548c0784db11d1ea0c46a7',
    messagingSenderId: '553715473254',
    projectId: 'romi-app-bc500',
    storageBucket: 'romi-app-bc500.firebasestorage.app',
    iosBundleId: 'com.example.romiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYphdqkVcCmOqZwep8nbOPDRZKGsaQeGE',
    appId: '1:553715473254:web:919e00ab8211a89e0c46a7',
    messagingSenderId: '553715473254',
    projectId: 'romi-app-bc500',
    authDomain: 'romi-app-bc500.firebaseapp.com',
    storageBucket: 'romi-app-bc500.firebasestorage.app',
  );

}